services:
  - type: web
    name: article-generator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: OPENAI_API_KEY
        value: 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
      - key: https://jebricol.com/wp-login.php?hide_my_wp=bricolage
        value: https://jebricol.com
      - key: WORDPRESS_USER
        value: Bricoleur
      - key: WORDPRESS_APP_PASSWORD
        value: Mgbk JrPy JD1H PIIR gFai 2cD1

